## Dwi Ageng Rohmatullah
## 2009106005
## Posttest 7

In [1]:
import tensorflow as tf

# Random Tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean = 10)
print(random_tensor)

tf.Tensor(
[[ 8.865948   9.112633  10.919816  10.046799   7.9363046]
 [10.028195  10.381554  10.696706   9.687963  11.20199  ]
 [ 8.839433  10.918514  10.332897   7.442403  11.039174 ]
 [10.322048  11.135388   9.047853   8.518225   9.982552 ]
 [10.836257   9.555759  10.527232  10.312455  10.034539 ]], shape=(5, 5), dtype=float32)


# Prime Tensor

### Dengan menggunakan list

In [3]:
prime = [[2,3,5,7,11], [13,17,19,23,29], [31,37,41,43,47], [53,59,61,67,71], [73,79,83,89,97]]

prime_tensor = tf.convert_to_tensor(prime, dtype=tf.float32)

prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

# Dimension Display

In [29]:
print(random_tensor.get_shape())

(5, 5)


In [5]:
print(prime_tensor.shape)

(5, 5)


# Arithmetic Operations

In [6]:
print(tf.matmul(prime_tensor,random_tensor))

tf.Tensor(
[[ 283.46683  287.02356  284.72876  259.43408  284.93225]
 [1005.3445  1035.6334  1033.517    931.68976 1023.95044]
 [1961.4564  2042.2106  2041.7788  1826.013   2013.9783 ]
 [3061.7156  3186.0405  3193.8025  2860.9622  3136.2146 ]
 [4142.8936  4309.56    4326.2173  3874.915   4242.356  ]], shape=(5, 5), dtype=float32)


In [7]:
print(tf.add(prime_tensor,random_tensor))

tf.Tensor(
[[ 10.865948  12.112633  15.919816  17.046799  18.936304]
 [ 23.028194  27.381554  29.696705  32.68796   40.20199 ]
 [ 39.83943   47.918514  51.332897  50.4424    58.039173]
 [ 63.32205   70.13539   70.04785   75.51823   80.98255 ]
 [ 83.83626   88.555756  93.52723   99.312454 107.03454 ]], shape=(5, 5), dtype=float32)


In [8]:
print(tf.subtract(prime_tensor,random_tensor))

tf.Tensor(
[[-6.8659477 -6.1126328 -5.919816  -3.0467987  3.0636954]
 [ 2.9718046  6.6184464  8.303294  13.312037  17.79801  ]
 [22.160568  26.081486  30.667103  35.5576    35.960827 ]
 [42.67795   47.864613  51.95215   58.481773  61.01745  ]
 [62.163742  69.444244  72.47277   78.687546  86.96546  ]], shape=(5, 5), dtype=float32)


In [9]:
print(tf.multiply(prime_tensor,random_tensor))

tf.Tensor(
[[ 17.731895  27.337898  54.59908   70.32759   87.29935 ]
 [130.36655  176.48642  203.23741  222.82314  324.85773 ]
 [274.0224   403.98502  423.64877  320.02332  518.8412  ]
 [547.06854  656.9879   551.91907  570.72107  708.76117 ]
 [791.04675  754.90497  873.76025  917.80853  973.3503  ]], shape=(5, 5), dtype=float32)


In [10]:
print(tf.divide(prime_tensor,random_tensor))

tf.Tensor(
[[0.2255822  0.32921332 0.45788318 0.6967394  1.3860356 ]
 [1.2963449  1.6375198  1.7762477  2.3740802  2.5888257 ]
 [3.5070124  3.3887393  3.9679093  5.777704   4.257565  ]
 [5.1346397  5.2984233  6.7419305  7.8654885  7.11241   ]
 [6.7366433  8.267265   7.8843136  8.630341   9.666613  ]], shape=(5, 5), dtype=float32)


# Nilai Minimum dan Maximum

In [14]:
max_kolom = tf.argmax(random_tensor, axis = 0)

print("nilai max berdasarkan kolom : ", max_kolom)

max_baris = tf.argmax(random_tensor, axis = 1)

print("nilai max berdasarkan baris : ", max_baris)

nilai max berdasarkan kolom :  tf.Tensor([4 3 0 4 1], shape=(5,), dtype=int64)
nilai max berdasarkan baris :  tf.Tensor([2 4 4 1 0], shape=(5,), dtype=int64)


In [17]:
min_kolom = tf.argmin(random_tensor, axis = 0)

print("nilai max berdasarkan kolom : ", min_kolom)

min_baris = tf.argmin(random_tensor, axis = 1)

print("nilai max berdasarkan baris : ", min_baris)

nilai max berdasarkan kolom :  tf.Tensor([2 0 3 2 0], shape=(5,), dtype=int64)
nilai max berdasarkan baris :  tf.Tensor([4 3 3 3 1], shape=(5,), dtype=int64)


# Tensor Concatenation

In [23]:
concat_tensor = tf.concat([prime_tensor,random_tensor], axis = 0)
print(concat_tensor)

tf.Tensor(
[[ 2.         3.         5.         7.        11.       ]
 [13.        17.        19.        23.        29.       ]
 [31.        37.        41.        43.        47.       ]
 [53.        59.        61.        67.        71.       ]
 [73.        79.        83.        89.        97.       ]
 [ 8.865948   9.112633  10.919816  10.046799   7.9363046]
 [10.028195  10.381554  10.696706   9.687963  11.20199  ]
 [ 8.839433  10.918514  10.332897   7.442403  11.039174 ]
 [10.322048  11.135388   9.047853   8.518225   9.982552 ]
 [10.836257   9.555759  10.527232  10.312455  10.034539 ]], shape=(10, 5), dtype=float32)


In [25]:
concat_tensor2 = tf.concat([prime_tensor,random_tensor], axis = 1)
print(concat_tensor2)

tf.Tensor(
[[ 2.         3.         5.         7.        11.         8.865948
   9.112633  10.919816  10.046799   7.9363046]
 [13.        17.        19.        23.        29.        10.028195
  10.381554  10.696706   9.687963  11.20199  ]
 [31.        37.        41.        43.        47.         8.839433
  10.918514  10.332897   7.442403  11.039174 ]
 [53.        59.        61.        67.        71.        10.322048
  11.135388   9.047853   8.518225   9.982552 ]
 [73.        79.        83.        89.        97.        10.836257
   9.555759  10.527232  10.312455  10.034539 ]], shape=(5, 10), dtype=float32)


In [26]:
print(concat_tensor.shape)
print(concat_tensor2.shape)

(10, 5)
(5, 10)


# Tensor Sorting

## Descending

In [27]:
prime_desc = tf.sort(prime_tensor, direction="DESCENDING")
print(prime_desc)

tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)


In [28]:
random_desc = tf.sort(random_tensor, direction="DESCENDING")
print(random_desc)

tf.Tensor(
[[10.919816  10.046799   9.112633   8.865948   7.9363046]
 [11.20199   10.696706  10.381554  10.028195   9.687963 ]
 [11.039174  10.918514  10.332897   8.839433   7.442403 ]
 [11.135388  10.322048   9.982552   9.047853   8.518225 ]
 [10.836257  10.527232  10.312455  10.034539   9.555759 ]], shape=(5, 5), dtype=float32)
